name: ChuckMalcomson
favicon: null
layout_spectrum: 0.37849
typography_spectrum: 0.8565181626472622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.2104993627872318
  saturation: 0.7384674383793026
  rhythmicContrast: 0.8208194028120488
purpose: []
